// Code generated by hertz generator.

package main

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/stonebirdjx/topx/biz/config"
	"github.com/stonebirdjx/topx/biz/dal"
	"github.com/stonebirdjx/topx/biz/middleware"
	"golang.org/x/time/rate"
)

func Init() error {
	g := config.ReadFromEnv()
	if err := g.Validate(); err != nil {
		return err
	}

	ctx := context.Background()
	middleware.NewLimiter(ctx, middleware.LimiterOptions{R: rate.Limit(g.RateLimit), B: g.Burst})

	if err := dal.MongoInit(ctx, dal.MongoOption{URI: g.MongoDBURI, DB: g.MongoDBDB}); err != nil {
		return err
	}

	return nil
}

func main() {
	hlog.Infof(config.ProgramBless())
	if err := Init(); err != nil {
		panic(err.Error())
	}

	// hertz
	h := server.Default(server.WithHostPorts(":6789"))

	register(h)
	h.Spin()

	// hlog.Infof(config.Thankyou())
}
